BEGIN;

-- Starting seed: one admin account + approved car brands/models from live DB.

INSERT INTO public.car_brands (id, name, is_approved) VALUES (1, 'Porsche', 't');
INSERT INTO public.car_brands (id, name, is_approved) VALUES (2, 'BMW', 't');
INSERT INTO public.car_brands (id, name, is_approved) VALUES (3, 'Audi', 't');
INSERT INTO public.car_brands (id, name, is_approved) VALUES (11, 'Seat', 't');
INSERT INTO public.car_brands (id, name, is_approved) VALUES (15, 'Volkswagen', 't');
INSERT INTO public.car_brands (id, name, is_approved) VALUES (16, 'Mercedes-Benz', 't');
INSERT INTO public.car_brands (id, name, is_approved) VALUES (17, 'Opel', 't');
INSERT INTO public.car_brands (id, name, is_approved) VALUES (19, 'Cupra', 't');
INSERT INTO public.car_brands (id, name, is_approved) VALUES (20, 'Skoda', 't');
INSERT INTO public.car_brands (id, name, is_approved) VALUES (21, 'Renault', 't');
INSERT INTO public.car_brands (id, name, is_approved) VALUES (22, 'Peugeot', 't');
INSERT INTO public.car_brands (id, name, is_approved) VALUES (23, 'Citroen', 't');
INSERT INTO public.car_brands (id, name, is_approved) VALUES (24, 'Toyota', 't');
INSERT INTO public.car_brands (id, name, is_approved) VALUES (25, 'Honda', 't');
INSERT INTO public.car_brands (id, name, is_approved) VALUES (26, 'Mazda', 't');
INSERT INTO public.car_brands (id, name, is_approved) VALUES (27, 'Ford', 't');
INSERT INTO public.car_brands (id, name, is_approved) VALUES (28, 'Nissan', 't');
INSERT INTO public.car_brands (id, name, is_approved) VALUES (29, 'Hyundai', 't');
INSERT INTO public.car_brands (id, name, is_approved) VALUES (30, 'Kia', 't');
INSERT INTO public.car_brands (id, name, is_approved) VALUES (31, 'Alfa Romeo', 't');
INSERT INTO public.car_brands (id, name, is_approved) VALUES (32, 'Volvo', 't');
INSERT INTO public.car_brands (id, name, is_approved) VALUES (33, 'Mini', 't');
INSERT INTO public.car_brands (id, name, is_approved) VALUES (34, 'Lexus', 't');
INSERT INTO public.car_brands (id, name, is_approved) VALUES (35, 'Subaru', 't');
INSERT INTO public.car_brands (id, name, is_approved) VALUES (36, 'Tesla', 't');
INSERT INTO public.car_brands (id, name, is_approved) VALUES (62, 'Saab', 't');
INSERT INTO public.car_brands (id, name, is_approved) VALUES (63, 'BYD', 't');
INSERT INTO public.car_brands (id, name, is_approved) VALUES (67, 'MG', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (1, 1, '911 992', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (2, 2, 'M3 G80', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (3, 3, 'RS6 C8', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (15, 1, '911 997 Carrera', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (16, 1, '911 991 Carrera', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (17, 1, '911 992 Carrera', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (18, 1, 'Cayman 987', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (19, 1, 'Cayman 981', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (20, 1, '718 Cayman 982', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (21, 1, 'Panamera 971', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (22, 1, 'Macan 95B', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (23, 1, 'Cayenne 958', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (24, 2, 'Seria 1 E87', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (25, 2, 'Seria 1 F20', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (26, 2, 'Seria 2 F22', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (27, 2, 'M2 F87', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (28, 2, 'Seria 3 E36', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (29, 2, 'Seria 3 E46', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (30, 2, 'Seria 3 E90', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (31, 2, 'Seria 3 F30', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (32, 2, 'Seria 3 G20', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (33, 2, 'M3 E46', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (34, 2, 'M3 E92', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (35, 2, 'M3 F80', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (37, 2, 'Seria 4 F32', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (38, 2, 'M4 F82', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (39, 2, 'M4 G82', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (40, 2, 'Seria 5 E39', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (41, 2, 'Seria 5 E60', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (42, 2, 'Seria 5 F10', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (43, 2, 'Seria 5 G30', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (44, 2, 'X3 E83', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (45, 2, 'X3 F25', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (46, 2, 'X5 E53', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (47, 2, 'X5 E70', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (48, 2, 'X5 G05', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (49, 3, 'A3 8L', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (50, 3, 'A3 8P', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (51, 3, 'A3 8V', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (52, 3, 'A3 8Y', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (53, 3, 'S3 8P', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (54, 3, 'S3 8V', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (55, 3, 'RS3 8V', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (56, 3, 'A4 B5', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (57, 3, 'A4 B6', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (58, 3, 'A4 B7', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (59, 3, 'A4 B8', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (60, 3, 'A4 B9', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (61, 3, 'RS4 B7', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (62, 3, 'RS4 B9', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (63, 3, 'A6 C5', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (64, 3, 'A6 C6', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (65, 3, 'A6 C7', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (66, 3, 'A6 C8', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (67, 3, 'RS6 C6', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (68, 3, 'RS6 C7', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (70, 3, 'TT 8N', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (71, 3, 'TT 8J', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (72, 3, 'TT 8S', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (73, 15, 'Golf IV', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (74, 15, 'Golf V', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (75, 15, 'Golf VI', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (76, 15, 'Golf VII', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (77, 15, 'Golf VIII', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (78, 15, 'Passat B5', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (79, 15, 'Passat B6', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (80, 15, 'Passat B7', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (81, 15, 'Passat B8', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (82, 15, 'Arteon 3H', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (83, 15, 'Scirocco III', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (84, 15, 'Polo 6N', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (85, 15, 'Polo 9N', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (86, 15, 'Polo 6R', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (87, 15, 'Polo AW', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (88, 15, 'Tiguan I', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (89, 15, 'Tiguan II', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (90, 16, 'Klasa A W176', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (91, 16, 'Klasa A W177', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (92, 16, 'CLA C117', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (93, 16, 'CLA C118', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (94, 16, 'Klasa C W203', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (95, 16, 'Klasa C W204', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (96, 16, 'Klasa C W205', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (97, 16, 'Klasa C W206', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (98, 16, 'Klasa E W211', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (99, 16, 'Klasa E W212', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (100, 16, 'Klasa E W213', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (101, 16, 'Klasa E W214', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (102, 16, 'CLS C219', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (103, 16, 'CLS C257', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (104, 16, 'GLC X253', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (105, 16, 'GLC X254', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (106, 17, 'Astra G', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (107, 17, 'Astra H', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (108, 17, 'Astra J', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (109, 17, 'Astra K', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (110, 17, 'Astra L', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (111, 17, 'Corsa C', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (112, 17, 'Corsa D', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (113, 17, 'Corsa E', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (114, 17, 'Corsa F', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (115, 17, 'Insignia A', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (116, 17, 'Insignia B', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (117, 17, 'Vectra B', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (118, 17, 'Vectra C', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (119, 17, 'Zafira A', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (120, 17, 'Zafira B', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (121, 17, 'Zafira C', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (122, 11, 'Leon I 1M', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (123, 11, 'Leon II 1P', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (124, 11, 'Leon III 5F', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (125, 11, 'Leon IV KL', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (126, 11, 'Ibiza III 6L', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (127, 11, 'Ibiza IV 6J', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (128, 11, 'Ibiza V KJ', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (129, 11, 'Exeo 3R', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (130, 11, 'Ateca 5FP', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (131, 19, 'Leon KL', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (132, 19, 'Formentor KM', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (133, 19, 'Ateca 5FP', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (134, 19, 'Born K1', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (135, 20, 'Fabia I 6Y', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (136, 20, 'Fabia II 5J', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (137, 20, 'Fabia III NJ', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (138, 20, 'Fabia IV PJ', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (139, 20, 'Octavia I 1U', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (140, 20, 'Octavia II 1Z', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (141, 20, 'Octavia III 5E', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (142, 20, 'Octavia IV NX', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (143, 20, 'Superb II 3T', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (144, 20, 'Superb III 3V', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (145, 20, 'Kodiaq I NS', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (146, 20, 'Scala NW', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (147, 21, 'Clio II', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (148, 21, 'Clio III', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (149, 21, 'Clio IV', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (150, 21, 'Clio V', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (151, 21, 'Megane II', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (152, 21, 'Megane III', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (153, 21, 'Megane IV', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (154, 21, 'Laguna II', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (155, 21, 'Laguna III', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (156, 21, 'Talisman', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (157, 21, 'Scenic III', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (158, 21, 'Scenic IV', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (159, 22, '206', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (160, 22, '207', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (161, 22, '208 I', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (162, 22, '208 II', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (163, 22, '308 I', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (164, 22, '308 II', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (165, 22, '308 III', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (166, 22, '407', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (167, 22, '508 I', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (168, 22, '508 II', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (169, 22, 'RCZ', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (170, 23, 'C4 I', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (171, 23, 'C4 II', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (172, 23, 'C4 III', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (173, 23, 'C5 I', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (174, 23, 'C5 II', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (175, 23, 'C5 X', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (176, 23, 'DS3', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (177, 23, 'Berlingo II', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (178, 23, 'Berlingo III', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (179, 24, 'Corolla E11', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (180, 24, 'Corolla E12', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (181, 24, 'Corolla E15', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (182, 24, 'Corolla E18', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (183, 24, 'Corolla E21', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (184, 24, 'Avensis T22', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (185, 24, 'Avensis T25', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (186, 24, 'Avensis T27', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (187, 24, 'Yaris XP10', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (188, 24, 'Yaris XP90', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (189, 24, 'Yaris XP130', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (190, 24, 'Yaris XP210', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (191, 24, 'GT86 ZN6', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (192, 24, 'Supra A90', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (193, 24, 'RAV4 XA30', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (194, 24, 'RAV4 XA40', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (195, 24, 'RAV4 XA50', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (196, 25, 'Civic VI', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (197, 25, 'Civic VII', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (198, 25, 'Civic VIII', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (199, 25, 'Civic IX', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (200, 25, 'Civic X', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (201, 25, 'Civic XI', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (202, 25, 'Accord VI', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (203, 25, 'Accord VII', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (204, 25, 'Accord VIII', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (205, 25, 'CR-V II', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (206, 25, 'CR-V III', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (207, 25, 'CR-V IV', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (208, 25, 'CR-V V', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (209, 25, 'S2000 AP1', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (210, 25, 'S2000 AP2', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (211, 26, 'Mazda 3 BK', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (212, 26, 'Mazda 3 BL', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (213, 26, 'Mazda 3 BM', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (214, 26, 'Mazda 3 BP', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (215, 26, 'Mazda 6 GG', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (216, 26, 'Mazda 6 GH', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (217, 26, 'Mazda 6 GJ', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (218, 26, 'Mazda 6 GL', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (219, 26, 'MX-5 NA', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (220, 26, 'MX-5 NB', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (221, 26, 'MX-5 NC', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (222, 26, 'MX-5 ND', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (223, 26, 'CX-5 KE', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (224, 26, 'CX-5 KF', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (225, 27, 'Focus Mk1', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (226, 27, 'Focus Mk2', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (227, 27, 'Focus Mk3', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (228, 27, 'Focus Mk4', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (229, 27, 'Mondeo Mk3', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (230, 27, 'Mondeo Mk4', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (231, 27, 'Mondeo Mk5', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (232, 27, 'Fiesta Mk5', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (233, 27, 'Fiesta Mk6', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (234, 27, 'Fiesta Mk7', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (235, 27, 'Fiesta Mk8', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (236, 27, 'Mustang S197', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (237, 27, 'Mustang S550', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (238, 27, 'Kuga Mk1', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (239, 27, 'Kuga Mk2', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (240, 27, 'Kuga Mk3', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (241, 28, 'Micra K11', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (242, 28, 'Micra K12', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (243, 28, 'Micra K13', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (244, 28, 'Micra K14', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (245, 28, '350Z Z33', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (246, 28, '370Z Z34', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (247, 28, 'GT-R R35', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (248, 28, 'Qashqai J10', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (249, 28, 'Qashqai J11', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (250, 28, 'Qashqai J12', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (251, 29, 'i20 PB', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (252, 29, 'i20 GB', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (253, 29, 'i20 BC3', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (254, 29, 'i30 FD', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (255, 29, 'i30 GD', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (256, 29, 'i30 PD', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (257, 29, 'Tucson LM', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (258, 29, 'Tucson TL', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (259, 29, 'Tucson NX4', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (260, 29, 'Kona OS', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (261, 29, 'Kona SX2', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (262, 29, 'Ioniq AE', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (263, 30, 'Ceed ED', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (264, 30, 'Ceed JD', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (265, 30, 'Ceed CD', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (266, 30, 'Proceed CD', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (267, 30, 'Sportage SL', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (268, 30, 'Sportage QL', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (269, 30, 'Sportage NQ5', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (270, 30, 'Stinger CK', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (271, 30, 'EV6 CV', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (272, 31, '147', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (273, 31, '156', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (274, 31, '159', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (275, 31, 'Giulietta 940', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (276, 31, 'Giulia 952', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (277, 31, 'Stelvio 949', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (278, 31, 'Brera 939', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (279, 32, 'S60 I', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (280, 32, 'S60 II', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (281, 32, 'S60 III', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (282, 32, 'V60 I', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (283, 32, 'V60 II', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (284, 32, 'XC60 I', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (285, 32, 'XC60 II', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (286, 32, 'V70 II', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (287, 32, 'V70 III', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (288, 32, 'XC90 I', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (289, 32, 'XC90 II', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (290, 33, 'Hatch R50', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (291, 33, 'Hatch R56', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (292, 33, 'Hatch F56', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (293, 33, 'Clubman R55', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (294, 33, 'Clubman F54', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (295, 33, 'Countryman R60', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (296, 33, 'Countryman F60', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (297, 34, 'IS XE10', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (298, 34, 'IS XE20', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (299, 34, 'IS XE30', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (300, 34, 'GS S160', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (301, 34, 'GS S190', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (302, 34, 'GS L10', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (303, 34, 'RC XC10', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (304, 34, 'NX AZ10', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (305, 34, 'NX AZ20', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (306, 35, 'Impreza GD', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (307, 35, 'Impreza GH', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (308, 35, 'Impreza GR', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (309, 35, 'Impreza GT', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (310, 35, 'WRX VA', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (311, 35, 'WRX VB', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (312, 35, 'Forester SG', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (313, 35, 'Forester SH', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (314, 35, 'Forester SJ', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (315, 35, 'Forester SK', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (316, 35, 'BRZ ZC6', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (317, 35, 'BRZ ZD8', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (318, 36, 'Model S', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (319, 36, 'Model 3', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (320, 36, 'Model X', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (321, 36, 'Model Y', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (632, 62, '9-3 II', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (633, 34, 'ES XV70', 't');
INSERT INTO public.car_models (id, brand_id, name, is_approved) VALUES (640, 67, 'Cyberster', 't');

INSERT INTO public.users (username, email, password, first_name, last_name, membership_tier, avatar_path, timezone, locale, last_login_at, created_at, updated_at, is_active, pseudonym, role, is_blocked, blocked_until, blocked_reason, blocked_is_permanent, blocked_at, admin_warning_message, admin_warning_sent_at, community_blocked_until, community_block_reason, community_block_is_permanent, community_blocked_at, marketplace_blocked_until, marketplace_block_reason, marketplace_block_is_permanent, marketplace_blocked_at) VALUES ('admin', 'admin@cockpit.local', '$2y$10$q8U/S2uloUegcLC8qYb4i.QJpyDbPFv28BY3LevXMiKcc7K9dpNJq', 'Admin', 'Admin', 'business', NULL, 'Europe/Warsaw', 'pl_PL', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE, 'admin', 'admin', FALSE, NULL, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, FALSE, NULL);
INSERT INTO public.user_settings (user_id) VALUES (currval('public.users_id_seq'));
SELECT setval('public.users_id_seq', GREATEST(COALESCE((SELECT MAX(id) FROM public.users), 1), 1), true);
SELECT setval('public.user_settings_id_seq', GREATEST(COALESCE((SELECT MAX(id) FROM public.user_settings), 1), 1), true);
SELECT setval('public.car_brands_id_seq', GREATEST(COALESCE((SELECT MAX(id) FROM public.car_brands), 1), 1), true);
SELECT setval('public.car_models_id_seq', GREATEST(COALESCE((SELECT MAX(id) FROM public.car_models), 1), 1), true);

COMMIT;

