INSERT INTO car_brands (name) VALUES
    ('Porsche'),
    ('BMW'),
    ('Audi'),
    ('Volkswagen'),
    ('Mercedes-Benz'),
    ('Opel'),
    ('Seat'),
    ('Cupra'),
    ('Skoda'),
    ('Renault'),
    ('Peugeot'),
    ('Citroen'),
    ('Toyota'),
    ('Honda'),
    ('Mazda'),
    ('Ford'),
    ('Nissan'),
    ('Hyundai'),
    ('Kia'),
    ('Alfa Romeo'),
    ('Volvo'),
    ('Mini'),
    ('Lexus'),
    ('Subaru'),
    ('Tesla')
ON CONFLICT (name) DO NOTHING;

INSERT INTO car_models (brand_id, name)
SELECT
    b.id,
    seeded_models.model_name
FROM (
    VALUES
        ('Porsche', '911 992'),
        ('BMW', 'M3 G80'),
        ('Audi', 'RS6 C8'),
        ('Porsche', '911 997 Carrera'),
        ('Porsche', '911 991 Carrera'),
        ('Porsche', '911 992 Carrera'),
        ('Porsche', 'Cayman 987'),
        ('Porsche', 'Cayman 981'),
        ('Porsche', '718 Cayman 982'),
        ('Porsche', 'Panamera 971'),
        ('Porsche', 'Macan 95B'),
        ('Porsche', 'Cayenne 958'),
        ('BMW', 'Seria 1 E87'),
        ('BMW', 'Seria 1 F20'),
        ('BMW', 'Seria 2 F22'),
        ('BMW', 'M2 F87'),
        ('BMW', 'Seria 3 E36'),
        ('BMW', 'Seria 3 E46'),
        ('BMW', 'Seria 3 E90'),
        ('BMW', 'Seria 3 F30'),
        ('BMW', 'Seria 3 G20'),
        ('BMW', 'M3 E46'),
        ('BMW', 'M3 E92'),
        ('BMW', 'M3 F80'),
        ('BMW', 'M3 G80'),
        ('BMW', 'Seria 4 F32'),
        ('BMW', 'M4 F82'),
        ('BMW', 'M4 G82'),
        ('BMW', 'Seria 5 E39'),
        ('BMW', 'Seria 5 E60'),
        ('BMW', 'Seria 5 F10'),
        ('BMW', 'Seria 5 G30'),
        ('BMW', 'X3 E83'),
        ('BMW', 'X3 F25'),
        ('BMW', 'X5 E53'),
        ('BMW', 'X5 E70'),
        ('BMW', 'X5 G05'),
        ('Audi', 'A3 8L'),
        ('Audi', 'A3 8P'),
        ('Audi', 'A3 8V'),
        ('Audi', 'A3 8Y'),
        ('Audi', 'S3 8P'),
        ('Audi', 'S3 8V'),
        ('Audi', 'RS3 8V'),
        ('Audi', 'A4 B5'),
        ('Audi', 'A4 B6'),
        ('Audi', 'A4 B7'),
        ('Audi', 'A4 B8'),
        ('Audi', 'A4 B9'),
        ('Audi', 'RS4 B7'),
        ('Audi', 'RS4 B9'),
        ('Audi', 'A6 C5'),
        ('Audi', 'A6 C6'),
        ('Audi', 'A6 C7'),
        ('Audi', 'A6 C8'),
        ('Audi', 'RS6 C6'),
        ('Audi', 'RS6 C7'),
        ('Audi', 'RS6 C8'),
        ('Audi', 'TT 8N'),
        ('Audi', 'TT 8J'),
        ('Audi', 'TT 8S'),
        ('Volkswagen', 'Golf IV'),
        ('Volkswagen', 'Golf V'),
        ('Volkswagen', 'Golf VI'),
        ('Volkswagen', 'Golf VII'),
        ('Volkswagen', 'Golf VIII'),
        ('Volkswagen', 'Passat B5'),
        ('Volkswagen', 'Passat B6'),
        ('Volkswagen', 'Passat B7'),
        ('Volkswagen', 'Passat B8'),
        ('Volkswagen', 'Arteon 3H'),
        ('Volkswagen', 'Scirocco III'),
        ('Volkswagen', 'Polo 6N'),
        ('Volkswagen', 'Polo 9N'),
        ('Volkswagen', 'Polo 6R'),
        ('Volkswagen', 'Polo AW'),
        ('Volkswagen', 'Tiguan I'),
        ('Volkswagen', 'Tiguan II'),
        ('Mercedes-Benz', 'Klasa A W176'),
        ('Mercedes-Benz', 'Klasa A W177'),
        ('Mercedes-Benz', 'CLA C117'),
        ('Mercedes-Benz', 'CLA C118'),
        ('Mercedes-Benz', 'Klasa C W203'),
        ('Mercedes-Benz', 'Klasa C W204'),
        ('Mercedes-Benz', 'Klasa C W205'),
        ('Mercedes-Benz', 'Klasa C W206'),
        ('Mercedes-Benz', 'Klasa E W211'),
        ('Mercedes-Benz', 'Klasa E W212'),
        ('Mercedes-Benz', 'Klasa E W213'),
        ('Mercedes-Benz', 'Klasa E W214'),
        ('Mercedes-Benz', 'CLS C219'),
        ('Mercedes-Benz', 'CLS C257'),
        ('Mercedes-Benz', 'GLC X253'),
        ('Mercedes-Benz', 'GLC X254'),
        ('Opel', 'Astra G'),
        ('Opel', 'Astra H'),
        ('Opel', 'Astra J'),
        ('Opel', 'Astra K'),
        ('Opel', 'Astra L'),
        ('Opel', 'Corsa C'),
        ('Opel', 'Corsa D'),
        ('Opel', 'Corsa E'),
        ('Opel', 'Corsa F'),
        ('Opel', 'Insignia A'),
        ('Opel', 'Insignia B'),
        ('Opel', 'Vectra B'),
        ('Opel', 'Vectra C'),
        ('Opel', 'Zafira A'),
        ('Opel', 'Zafira B'),
        ('Opel', 'Zafira C'),
        ('Seat', 'Leon I 1M'),
        ('Seat', 'Leon II 1P'),
        ('Seat', 'Leon III 5F'),
        ('Seat', 'Leon IV KL'),
        ('Seat', 'Ibiza III 6L'),
        ('Seat', 'Ibiza IV 6J'),
        ('Seat', 'Ibiza V KJ'),
        ('Seat', 'Exeo 3R'),
        ('Seat', 'Ateca 5FP'),
        ('Cupra', 'Leon KL'),
        ('Cupra', 'Formentor KM'),
        ('Cupra', 'Ateca 5FP'),
        ('Cupra', 'Born K1'),
        ('Skoda', 'Fabia I 6Y'),
        ('Skoda', 'Fabia II 5J'),
        ('Skoda', 'Fabia III NJ'),
        ('Skoda', 'Fabia IV PJ'),
        ('Skoda', 'Octavia I 1U'),
        ('Skoda', 'Octavia II 1Z'),
        ('Skoda', 'Octavia III 5E'),
        ('Skoda', 'Octavia IV NX'),
        ('Skoda', 'Superb II 3T'),
        ('Skoda', 'Superb III 3V'),
        ('Skoda', 'Kodiaq I NS'),
        ('Skoda', 'Scala NW'),
        ('Renault', 'Clio II'),
        ('Renault', 'Clio III'),
        ('Renault', 'Clio IV'),
        ('Renault', 'Clio V'),
        ('Renault', 'Megane II'),
        ('Renault', 'Megane III'),
        ('Renault', 'Megane IV'),
        ('Renault', 'Laguna II'),
        ('Renault', 'Laguna III'),
        ('Renault', 'Talisman'),
        ('Renault', 'Scenic III'),
        ('Renault', 'Scenic IV'),
        ('Peugeot', '206'),
        ('Peugeot', '207'),
        ('Peugeot', '208 I'),
        ('Peugeot', '208 II'),
        ('Peugeot', '308 I'),
        ('Peugeot', '308 II'),
        ('Peugeot', '308 III'),
        ('Peugeot', '407'),
        ('Peugeot', '508 I'),
        ('Peugeot', '508 II'),
        ('Peugeot', 'RCZ'),
        ('Citroen', 'C4 I'),
        ('Citroen', 'C4 II'),
        ('Citroen', 'C4 III'),
        ('Citroen', 'C5 I'),
        ('Citroen', 'C5 II'),
        ('Citroen', 'C5 X'),
        ('Citroen', 'DS3'),
        ('Citroen', 'Berlingo II'),
        ('Citroen', 'Berlingo III'),
        ('Toyota', 'Corolla E11'),
        ('Toyota', 'Corolla E12'),
        ('Toyota', 'Corolla E15'),
        ('Toyota', 'Corolla E18'),
        ('Toyota', 'Corolla E21'),
        ('Toyota', 'Avensis T22'),
        ('Toyota', 'Avensis T25'),
        ('Toyota', 'Avensis T27'),
        ('Toyota', 'Yaris XP10'),
        ('Toyota', 'Yaris XP90'),
        ('Toyota', 'Yaris XP130'),
        ('Toyota', 'Yaris XP210'),
        ('Toyota', 'GT86 ZN6'),
        ('Toyota', 'Supra A90'),
        ('Toyota', 'RAV4 XA30'),
        ('Toyota', 'RAV4 XA40'),
        ('Toyota', 'RAV4 XA50'),
        ('Honda', 'Civic VI'),
        ('Honda', 'Civic VII'),
        ('Honda', 'Civic VIII'),
        ('Honda', 'Civic IX'),
        ('Honda', 'Civic X'),
        ('Honda', 'Civic XI'),
        ('Honda', 'Accord VI'),
        ('Honda', 'Accord VII'),
        ('Honda', 'Accord VIII'),
        ('Honda', 'CR-V II'),
        ('Honda', 'CR-V III'),
        ('Honda', 'CR-V IV'),
        ('Honda', 'CR-V V'),
        ('Honda', 'S2000 AP1'),
        ('Honda', 'S2000 AP2'),
        ('Mazda', 'Mazda 3 BK'),
        ('Mazda', 'Mazda 3 BL'),
        ('Mazda', 'Mazda 3 BM'),
        ('Mazda', 'Mazda 3 BP'),
        ('Mazda', 'Mazda 6 GG'),
        ('Mazda', 'Mazda 6 GH'),
        ('Mazda', 'Mazda 6 GJ'),
        ('Mazda', 'Mazda 6 GL'),
        ('Mazda', 'MX-5 NA'),
        ('Mazda', 'MX-5 NB'),
        ('Mazda', 'MX-5 NC'),
        ('Mazda', 'MX-5 ND'),
        ('Mazda', 'CX-5 KE'),
        ('Mazda', 'CX-5 KF'),
        ('Ford', 'Focus Mk1'),
        ('Ford', 'Focus Mk2'),
        ('Ford', 'Focus Mk3'),
        ('Ford', 'Focus Mk4'),
        ('Ford', 'Mondeo Mk3'),
        ('Ford', 'Mondeo Mk4'),
        ('Ford', 'Mondeo Mk5'),
        ('Ford', 'Fiesta Mk5'),
        ('Ford', 'Fiesta Mk6'),
        ('Ford', 'Fiesta Mk7'),
        ('Ford', 'Fiesta Mk8'),
        ('Ford', 'Mustang S197'),
        ('Ford', 'Mustang S550'),
        ('Ford', 'Kuga Mk1'),
        ('Ford', 'Kuga Mk2'),
        ('Ford', 'Kuga Mk3'),
        ('Nissan', 'Micra K11'),
        ('Nissan', 'Micra K12'),
        ('Nissan', 'Micra K13'),
        ('Nissan', 'Micra K14'),
        ('Nissan', '350Z Z33'),
        ('Nissan', '370Z Z34'),
        ('Nissan', 'GT-R R35'),
        ('Nissan', 'Qashqai J10'),
        ('Nissan', 'Qashqai J11'),
        ('Nissan', 'Qashqai J12'),
        ('Hyundai', 'i20 PB'),
        ('Hyundai', 'i20 GB'),
        ('Hyundai', 'i20 BC3'),
        ('Hyundai', 'i30 FD'),
        ('Hyundai', 'i30 GD'),
        ('Hyundai', 'i30 PD'),
        ('Hyundai', 'Tucson LM'),
        ('Hyundai', 'Tucson TL'),
        ('Hyundai', 'Tucson NX4'),
        ('Hyundai', 'Kona OS'),
        ('Hyundai', 'Kona SX2'),
        ('Hyundai', 'Ioniq AE'),
        ('Kia', 'Ceed ED'),
        ('Kia', 'Ceed JD'),
        ('Kia', 'Ceed CD'),
        ('Kia', 'Proceed CD'),
        ('Kia', 'Sportage SL'),
        ('Kia', 'Sportage QL'),
        ('Kia', 'Sportage NQ5'),
        ('Kia', 'Stinger CK'),
        ('Kia', 'EV6 CV'),
        ('Alfa Romeo', '147'),
        ('Alfa Romeo', '156'),
        ('Alfa Romeo', '159'),
        ('Alfa Romeo', 'Giulietta 940'),
        ('Alfa Romeo', 'Giulia 952'),
        ('Alfa Romeo', 'Stelvio 949'),
        ('Alfa Romeo', 'Brera 939'),
        ('Volvo', 'S60 I'),
        ('Volvo', 'S60 II'),
        ('Volvo', 'S60 III'),
        ('Volvo', 'V60 I'),
        ('Volvo', 'V60 II'),
        ('Volvo', 'XC60 I'),
        ('Volvo', 'XC60 II'),
        ('Volvo', 'V70 II'),
        ('Volvo', 'V70 III'),
        ('Volvo', 'XC90 I'),
        ('Volvo', 'XC90 II'),
        ('Mini', 'Hatch R50'),
        ('Mini', 'Hatch R56'),
        ('Mini', 'Hatch F56'),
        ('Mini', 'Clubman R55'),
        ('Mini', 'Clubman F54'),
        ('Mini', 'Countryman R60'),
        ('Mini', 'Countryman F60'),
        ('Lexus', 'IS XE10'),
        ('Lexus', 'IS XE20'),
        ('Lexus', 'IS XE30'),
        ('Lexus', 'GS S160'),
        ('Lexus', 'GS S190'),
        ('Lexus', 'GS L10'),
        ('Lexus', 'RC XC10'),
        ('Lexus', 'NX AZ10'),
        ('Lexus', 'NX AZ20'),
        ('Subaru', 'Impreza GD'),
        ('Subaru', 'Impreza GH'),
        ('Subaru', 'Impreza GR'),
        ('Subaru', 'Impreza GT'),
        ('Subaru', 'WRX VA'),
        ('Subaru', 'WRX VB'),
        ('Subaru', 'Forester SG'),
        ('Subaru', 'Forester SH'),
        ('Subaru', 'Forester SJ'),
        ('Subaru', 'Forester SK'),
        ('Subaru', 'BRZ ZC6'),
        ('Subaru', 'BRZ ZD8'),
        ('Tesla', 'Model S'),
        ('Tesla', 'Model 3'),
        ('Tesla', 'Model X'),
        ('Tesla', 'Model Y')
) AS seeded_models(brand_name, model_name)
JOIN car_brands b ON b.name = seeded_models.brand_name
ON CONFLICT (brand_id, name) DO NOTHING;
