INSERT INTO users (
    username,
    email,
    password,
    first_name,
    last_name,
    pseudonym,
    membership_tier,
    avatar_path,
    timezone,
    locale,
    last_login_at,
    is_active
) VALUES
    ('natalia_wisniewska', 'natalia.wisniewska@example.com', '$2y$10$plKoUxhfNjt2JXLRrRRPweKQSs6kbFstQuBST33xit3QP7Z4QPe62', 'Natalia', 'Wiśniewska', 'NatiRacer', 'free', NULL, 'Europe/Warsaw', 'pl_PL', NULL, TRUE),
    ('bartosz_wojcik', 'bartosz.wojcik@example.com', '$2y$10$m7ysXUX4o4hP/LgQqmbSA.B8UVuxOup3xvuQXKmE/1j0EyH/phH0a', 'Bartosz', 'Wójcik', 'BartekVAG', 'free', NULL, 'Europe/Warsaw', 'pl_PL', NULL, TRUE),
    ('oliwia_kaminska', 'oliwia.kaminska@example.com', '$2y$10$u0GiqoqMqbQDEPD9GRFvq.yVl/6XUkkjUqgHkFUO9lZVKoH0O.NJK', 'Oliwia', 'Kamińska', 'OliGarage', 'free', NULL, 'Europe/Warsaw', 'pl_PL', NULL, TRUE),
    ('piotr_lewandowski', 'piotr.lewandowski@example.com', '$2y$10$ebaHvgC.XK63CfvQjkvDoOd8QCjNCyOoJQQklm9kGgLsN/x7ub.8q', 'Piotr', 'Lewandowski', 'PiotrekGTI', 'free', NULL, 'Europe/Warsaw', 'pl_PL', NULL, TRUE),
    ('zuzanna_dabrowska', 'zuzanna.dabrowska@example.com', '$2y$10$FaKEvtBLbWgAD6Zxr73wL.qT9cHI5h3hB30zgPbsDi9NhluyNVIfW', 'Zuzanna', 'Dąbrowska', 'ZuzaTurbo', 'free', NULL, 'Europe/Warsaw', 'pl_PL', NULL, TRUE),
    ('mateusz_mazur', 'mateusz.mazur@example.com', '$2y$10$lXqRPtKoSLdUCRQjnAEVm.NoFnvzBYNlpidWS82xfJ1Z9OCrH5I/m', 'Mateusz', 'Mazur', 'MatiDetailer', 'free', NULL, 'Europe/Warsaw', 'pl_PL', NULL, TRUE),
    ('karolina_kaczmarek', 'karolina.kaczmarek@example.com', '$2y$10$roKRgXrBfUZEJc7MAHYRU.I8eRJy6bSGlFKx10g.OgOwzEPSHLg2e', 'Karolina', 'Kaczmarek', 'KaroSpeed', 'free', NULL, 'Europe/Warsaw', 'pl_PL', NULL, TRUE),
    ('tomasz_krol', 'tomasz.krol@example.com', '$2y$10$tJvdvEHqOms51EfW75fUuOHIm1eMnYkpAfJlPrGpNuwG3WNj.hHo.', 'Tomasz', 'Król', 'TomekRacing', 'free', NULL, 'Europe/Warsaw', 'pl_PL', NULL, TRUE),
    ('wiktoria_pawlak', 'wiktoria.pawlak@example.com', '$2y$10$wdWBFoOzvUPPTX8WPRMJiuECHyRLEOjz6VWvu3zqUukt22ozhGLc6', 'Wiktoria', 'Pawlak', 'WikiGarage', 'free', NULL, 'Europe/Warsaw', 'pl_PL', NULL, TRUE),
    ('patryk_szymanski', 'patryk.szymanski@example.com', '$2y$10$2.1BvYwPQmHNBBEG2cECJe7X6i.uoxuVpUWcgYWsPWGkWqwXoi41a', 'Patryk', 'Szymański', 'PatrykBoost', 'free', NULL, 'Europe/Warsaw', 'pl_PL', NULL, TRUE),
    ('aleksandra_wozniak', 'aleksandra.wozniak@example.com', '$2y$10$vpbmrLd3nqnEfuJwZJiwtO.l5tT5HnU7gml6JqK8oNrNVIqwEbZOe', 'Aleksandra', 'Woźniak', 'OlaDetailing', 'free', NULL, 'Europe/Warsaw', 'pl_PL', NULL, TRUE),
    ('dawid_grabowski', 'dawid.grabowski@example.com', '$2y$10$er.AX25Z1Pn7c.ptxLjpD.614tJUlKwPFob5EamB1MaJzFYUQE/e6', 'Dawid', 'Grabowski', 'DawidV8', 'free', NULL, 'Europe/Warsaw', 'pl_PL', NULL, TRUE),
    ('maja_jankowska', 'maja.jankowska@example.com', '$2y$10$XJEyhepr3n0wNLUbODieN.aqt4je/U3wCr6aAP3OasY3n35Hv9B7e', 'Maja', 'Jankowska', 'MajaDrive', 'free', NULL, 'Europe/Warsaw', 'pl_PL', NULL, TRUE),
    ('filip_michalski', 'filip.michalski@example.com', '$2y$10$7FqD3voiBkxOSGUzS6mAae/oq9lJyaYcsaMXRiNCkfyPTGbvNGseC', 'Filip', 'Michalski', 'FilipGT', 'free', NULL, 'Europe/Warsaw', 'pl_PL', NULL, TRUE),
    ('weronika_piotrowska', 'weronika.piotrowska@example.com', '$2y$10$Od3b2V/kDazp6u068cW2burZ60KNa9Es92Ls6hmF7F8.8hZiw9N2a', 'Weronika', 'Piotrowska', 'WeraTurbo', 'free', NULL, 'Europe/Warsaw', 'pl_PL', NULL, TRUE),
    ('jakub_zajac', 'jakub.zajac@example.com', '$2y$10$//L/E715vP4a2tdkwcrSKO7lg31/jEk4qjMwlRFmjlxFwzpEpKCTi', 'Jakub', 'Zając', 'KubaMechanik', 'free', NULL, 'Europe/Warsaw', 'pl_PL', NULL, TRUE),
    ('amelia_sikora', 'amelia.sikora@example.com', '$2y$10$kPBwKjA0ly2ZzxSIZZ51Ruvg0cwI8tucJ/vXOTl/UiIg8mXROqEz6', 'Amelia', 'Sikora', 'AmiRacer', 'free', NULL, 'Europe/Warsaw', 'pl_PL', NULL, TRUE),
    ('marcin_baran', 'marcin.baran@example.com', '$2y$10$nfwjKr/yKT62b.IAi045mO05ihU9m/9mIcatn2Ogj.Xp3qVwBic8K', 'Marcin', 'Baran', 'MarcinGarage', 'free', NULL, 'Europe/Warsaw', 'pl_PL', NULL, TRUE),
    ('laura_wrobel', 'laura.wrobel@example.com', '$2y$10$WJ7jG9BxgzWQ4YPZeYGzBuMXEPrvg5vcbzI72kiBCnIZwYG2Hi0Ey', 'Laura', 'Wróbel', 'LauraCars', 'free', NULL, 'Europe/Warsaw', 'pl_PL', NULL, TRUE),
    ('dominik_lis', 'dominik.lis@example.com', '$2y$10$7c0Iy0zWuMk22IGg2lC2xOURI8NtXr5e7xdidX/QZr3nizu6kyLjC', 'Dominik', 'Lis', 'DominikBoost', 'free', NULL, 'Europe/Warsaw', 'pl_PL', NULL, TRUE),
    ('nikola_czarnecka', 'nikola.czarnecka@example.com', '$2y$10$1eOrzrJ7w5q8dy4wSR7Tc.UHvn4qi0hd9h.bjOE9yrFeO/bV8zlou', 'Nikola', 'Czarnecka', 'NikiDrive', 'free', NULL, 'Europe/Warsaw', 'pl_PL', NULL, TRUE),
    ('szymon_kubiak', 'szymon.kubiak@example.com', '$2y$10$gceMRGIDocw7H.4MT2DuMetJGuHscERrPS2nnxsa8CqzsQmhdBpqm', 'Szymon', 'Kubiak', 'SzymonTurbo', 'free', NULL, 'Europe/Warsaw', 'pl_PL', NULL, TRUE),
    ('gabriela_rutkowska', 'gabriela.rutkowska@example.com', '$2y$10$.EEcve7kgaMEAzLweEFbcuintBr2L0Oo7ZXleeZ.jE6XHpaj4JsBW', 'Gabriela', 'Rutkowska', 'GabiAuto', 'free', NULL, 'Europe/Warsaw', 'pl_PL', NULL, TRUE),
    ('lukasz_olszewski', 'lukasz.olszewski@example.com', '$2y$10$i1oQxIjivspjWvJXLVTOUuiH0z9WN9f2QZVMVM10Pi8LWggX0Z62C', 'Łukasz', 'Olszewski', 'LukiVAG', 'free', NULL, 'Europe/Warsaw', 'pl_PL', NULL, TRUE),
    ('emilia_kowalczyk', 'emilia.kowalczyk@example.com', '$2y$10$sFWdSkAaYsFmeGQdikjuVeDRlOszg0hXKsW62RG5rXF8az4dpnNW.', 'Emilia', 'Kowalczyk', 'EmiDetailer', 'free', NULL, 'Europe/Warsaw', 'pl_PL', NULL, TRUE),
    ('kacper_sobczak', 'kacper.sobczak@example.com', '$2y$10$fbGe4HWW3SYPltyCqfpG2.SCbqdsbvF6YtKSgLRAP4qvA.qD04J12', 'Kacper', 'Sobczak', 'KacperGTI', 'free', NULL, 'Europe/Warsaw', 'pl_PL', NULL, TRUE)
ON CONFLICT (username) DO UPDATE
SET
    email = EXCLUDED.email,
    password = EXCLUDED.password,
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    pseudonym = EXCLUDED.pseudonym,
    membership_tier = 'free',
    avatar_path = NULL,
    timezone = 'Europe/Warsaw',
    locale = 'pl_PL',
    last_login_at = NULL,
    is_active = TRUE;

INSERT INTO user_settings (user_id)
SELECT u.id
FROM users u
WHERE u.username IN (
    'natalia_wisniewska',
    'bartosz_wojcik',
    'oliwia_kaminska',
    'piotr_lewandowski',
    'zuzanna_dabrowska',
    'mateusz_mazur',
    'karolina_kaczmarek',
    'tomasz_krol',
    'wiktoria_pawlak',
    'patryk_szymanski',
    'aleksandra_wozniak',
    'dawid_grabowski',
    'maja_jankowska',
    'filip_michalski',
    'weronika_piotrowska',
    'jakub_zajac',
    'amelia_sikora',
    'marcin_baran',
    'laura_wrobel',
    'dominik_lis',
    'nikola_czarnecka',
    'szymon_kubiak',
    'gabriela_rutkowska',
    'lukasz_olszewski',
    'emilia_kowalczyk',
    'kacper_sobczak'
)
ON CONFLICT (user_id) DO NOTHING;
